[package]
name = "mdbook-shiftinclude"
version = "0.1.0"
authors = ["David Drysdale <dmd@lurklurk.org>"]
edition = "2021"
license = "MPL-2.0"
description = "mdbook preprocessor for file inclusion with shift"
repository = "https://github.com/daviddrysdale/mdbook-shiftinclude"
keywords = ["mdbook", "preprocessor"]
categories = ["text-processing"]

[dependencies]
anyhow = "1.0.71"
clap = "2.*"
env_logger = "^0.11.1"
log = "^0.4.17"
mdbook = "^0.4.37"
once_cell = "1.17.1"
regex = "1.8.1"
serde_json = "1.*"
